### ISSUE TITLE
Header changes between screens

### ISSUE THREAD

**Issue by siddharthvp** [Ankit-Gupta18/Edit-Request-Wizard#10]
Header changes from "EDIT REQUEST WIZARD" on one screen to "EDIT WIZARD" on the next - keep it consistent. I suggest not using ALL CAPS because wikipedians in particular don't like that

**Comment by Ankit-Gupta18** [comment]
@siddharthvp @enterprisey 
![image](https://user-images.githubusercontent.com/72732381/181938651-e645f913-bb7b-4957-bd8c-d79878aada99.png)
Does it look good with this header? Or any improvements?
