### ISSUE TITLE
Unusual font face in tooltip 

### ISSUE THREAD

**Issue by siddharthvp** [Ankit-Gupta18/Edit-Request-Wizard#11]
<img width="383" alt="Screenshot 2022-07-31 at 12 06 13 AM" src="https://user-images.githubusercontent.com/31818903/181937037-de158781-4c80-4728-8dc5-9f4423a04bb9.png">

please use standard typefaces only - so that everything has a consistent look and feel, see https://careerfoundry.com/en/blog/ui-design/the-importance-of-consistency-in-ui-design

**Comment by Ankit-Gupta18** [comment]
![image](https://user-images.githubusercontent.com/72732381/181940026-6423b430-1244-499d-83c6-8c08d93f8b19.png)
Is it fine to make it italic? I removed cursive font
