### ISSUE TITLE
Backend request IP logging

### ISSUE THREAD

**Issue by siddharthvp** [Ankit-Gupta18/Edit-Request-Wizard#14]
<img width="716" alt="Screenshot 2022-08-07 at 11 48 34 AM" src="https://user-images.githubusercontent.com/31818903/183278035-f0e20b0b-31bb-4ce7-a669-20abaa0252b0.png">

Please don't try to log the IP address - anyway, it appears toolforge has a front proxy that's scrubbing out this private information since we're seeing just the private IPs here. 

(also, can you change "Example app"?)

**Comment by Ankit-Gupta18** [comment]
> <img alt="Screenshot 2022-08-07 at 11 48 34 AM" width="716" src="https://user-images.githubusercontent.com/31818903/183278035-f0e20b0b-31bb-4ce7-a669-20abaa0252b0.png">
> 
> Please don't try to log the IP address - anyway, it appears toolforge has a front proxy that's scrubbing out this private information since we're seeing just the private IPs here.
> 
> (also, can you change "Example app"?)

I was using `short` format should I use the `tiny` format now?
![image](https://user-images.githubusercontent.com/72732381/183337258-a9c5a035-ca9f-4cbe-b0a8-ab338f622317.png)

**Comment by Ankit-Gupta18** [comment]
What is example app?

**Comment by siddharthvp** [comment]
Yeah tiny format is ok.

> What is example app?

Exactly. It shouldn't say "Example app" in the first line of logs.
