### ISSUE TITLE
Add tests for backend

### ISSUE THREAD

**Issue by siddharthvp** [Ankit-Gupta18/Edit-Request-Wizard#15]
* Factor out the working logic in the code to separate files 
* Set up unit tests for the above 
* Adjust the deployment pipeline to run the tests as well - deployment should take place only if tests pass

**Comment by Ankit-Gupta18** [comment]
Can you please explain this in detail(with examples if possible) since I didn't understand the issue very clearly and never tried this before too?

**Comment by siddharthvp** [comment]
The jest documentation, https://jestjs.io/docs/getting-started, is a good introduction to unit testing.
