### ISSUE TITLE
Display copyright boilerplate next to "Publish" button

### ISSUE THREAD

**Issue by enterprisey** [Ankit-Gupta18/Edit-Request-Wizard#19]
Load dynamically from https://en.wikipedia.org/wiki/MediaWiki:Wikimedia-copyrightwarning

**Comment by Ankit-Gupta18** [comment]
Where should it go exactly? (If you could add a screenshot)

**Comment by xaosflux** [comment]
It could go right down here:
![image](https://user-images.githubusercontent.com/99730619/183674444-83719bff-cdc7-41bd-b8ce-806b9fff00bf.png)
Compare to how reply tool loads it below the input area:
![image](https://user-images.githubusercontent.com/99730619/183674832-8fb1b715-2790-4363-a3ce-c0188e3e86bd.png)
To get around the verbiage mismatch, perhaps the wizard can change the label from "Send Edit Request" to "Publish Edit Request" - that way you don't have to fork the copyright or add more text that "Send equals Publish" ?

**Comment by Ankit-Gupta18** [comment]
> It could go right down here: ![image](https://user-images.githubusercontent.com/99730619/183674444-83719bff-cdc7-41bd-b8ce-806b9fff00bf.png) Compare to how reply tool loads it below the input area: ![image](https://user-images.githubusercontent.com/99730619/183674832-8fb1b715-2790-4363-a3ce-c0188e3e86bd.png) To get around the verbiage mismatch, perhaps the wizard can change the label from "Send Edit Request" to "Publish Edit Request" - that way you don't have to fork the copyright or add more text that "Send equals Publish" ?

I have implemented it. And it's live now. Thanku
