### ISSUE TITLE
Main menu

### ISSUE THREAD

**Issue by enterprisey** [Ankit-Gupta18/Edit-Request-Wizard#23]
options: "add fact", "change fact", "fix grammar", etc

**Comment by enterprisey** [comment]
detailed spec

add a new panel at the beginning that looks roughly like this with four buttons:
![image](https://user-images.githubusercontent.com/1981364/187017431-19c8add8-3f54-43cc-a331-b64ab0a025d0.png)

(you can rename the buttons as you wish. the buttons are meant to be aligned in a grid.)

 - the first button, "Add Fact", takes you to the wizard as it currently exists
 - the second button, "Fix Factual Error", also takes you through the same wizard, although the text for some of the steps will be different, and the first step should now be "select the text that needs to be fixed". instead of rephrasing the quote, the text area should be pre-filled with the text the user selected, and they can rewrite it.
 - the third button, "Remove Content", also takes you through the same wizard. the first step will be "select the text that needs to be removed", and instead of rephrasing the quote, the user can select from a list of options for removal, with an "other" option.
 - the fourth button, "Do Something Else", just takes you to the editor.

**Comment by Ankit-Gupta18** [comment]
Few follow-up questions: 
1. How does it handle editing grammar errors?
2. For "Fix factual Error", don't we need a source? Just two panels - select text and rewrite panel?
3. For "Remove Content", just two panels? also, what are the options to be listed for removal?
4. For "Do something else", how to redirect it to the visual editor?

**Comment by Ankit-Gupta18** [comment]
Also, how is this design, any suggestions?
![image](https://user-images.githubusercontent.com/72732381/187028448-3e5a3e58-8241-4ca3-b22a-464355965851.png)

**Comment by enterprisey** [comment]
Design looks fine

 - Grammar edits: covered under do some else
 - factual error, source is needed because otherwise we get low-quality edits
 - remove content: source is optional. Maybe add a skip button
 - do something else: use https://doc.wikimedia.org/mediawiki-core/REL1_29/js/#!/api/mw.util-method-getUrl - hover over the visual edit tab on an article. There should be specific values for action= and veaction= and they should be passed to getUrl
