### ISSUE TITLE
Headers and sidebars become greyed out on placement selection screen

### ISSUE THREAD

**Issue by siddharthvp** [Ankit-Gupta18/Edit-Request-Wizard#9]
This is weird, looks unintentional?

![](https://cdn.discordapp.com/attachments/1002967501287727106/1002968698853806152/Screenshot_2022-07-30_at_9.28.55_PM.png)

**Comment by enterprisey** [comment]
It's intentional, and was meant to indicate that selection in the gray areas shouldn't be allowed. We can get rid of it if that meaning is unclear, which seems to be the case.

**Comment by Ankit-Gupta18** [comment]
> It's intentional, and was meant to indicate that selection in the gray areas shouldn't be allowed. We can get rid of it if that meaning is unclear, which seems to be the case.

Yes, that was something which was pointed by my friends too, we need to think of some better UI maybe.

**Comment by Ankit-Gupta18** [comment]
@siddharthvp @enterprisey 
When we click on generate button through citoid, it has some moving grey lines animation. Can we use it here? If yes, how can we do this in OOUI?

**Comment by enterprisey** [comment]
I imagine the moving lines animation might be a bit distracting. One option is just dropping the effect altogether.
